win**.mak: Forward DMD for copyDir
The target might require the host compiler, e.g. when run as a standalone.

Previously `make -f .\win32.mak copydir` failed due to `$(DMD)` expanding
to the empty string:

```
"make" -f mak/WINDOWS copydir HOST_DMD="dmd" MODEL=32 IMPDIR="import"
conf= -c -o- -Isrc -Iimport -Hfimport\core\sync\barrier.di src\core\sync\barrier.d
Error: 'conf=' not found
```